name = "leetcodebot"
type = "webpack"

account_id = "ad8043c172f95e93320d232f65f696f9"
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-14"

kv_namespaces = [
    { binding = "LEETCODE", id = "7c36e29ff4664667b6cbf2c1e8363292" }
]

[triggers]
crons = ["*/5 * * * *", "0 16 * * *"]
